name: Build

on: push

jobs:
  build:
    name: Test Node job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        node: [10, 12, 14]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - node: 10
            os: macos-latest
            experimental: true
    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Alex
          MIDDLE_NAME: V
          LAST_NAME: Krupskiy
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
